<a href="https://colab.research.google.com/github/MDMohaymenUlAnam/CSE-4554-Machine-Learning/blob/main/190042142_MD_Mohaymen_Ul_Anam_Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# task1:
a = np.random.randint(10,size =10)
print(a)


[1 6 5 7 0 0 1 0 3 2]


In [ ]:
# task2
b = np.random.randint(10, size = (7,6))
c = np.reshape(b,(3,14))
print(c)


[[5 0 6 5 0 0 2 0 8 6 9 7 5 5]
 [7 3 4 9 2 1 8 2 6 0 2 9 8 3]
 [0 5 1 7 1 1 3 0 2 4 4 4 3 9]]


In [ ]:
# task3
d = np.arange(10)
for num in d:
  if(num % 2 ==0):
    print(num)


0
2
4
6
8


In [ ]:
# task4:

d = np.arange(10)

d[d % 2 == 0] = -1
print(d)





[-1  1 -1  3 -1  5 -1  7 -1  9]


In [ ]:
# task5
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
output = np.where(arr % 2 ==1, -1,arr)
print(arr)
print(output)


[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [ ]:
# Task 06:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.where(a==b))





(array([1, 3, 5, 7]),)


In [ ]:
# Task 07:
a = np.array([2, 6, 1, 9, 10, 3, 27])
result = np.where((a >= 5) & (a <= 10))
print(a[result])





[ 6  9 10]


In [ ]:
# task8
a = np.zeros(10)
b = np.ones(10)
c = np.concatenate([a, b])
print(c)



[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
# task8
a = np.zeros(10)
b = np.ones(10)
d = a.reshape(10,1)
e = b.reshape(10,1)
f = np.concatenate([d, e])
print(f)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [ ]:
# task9:
a = np.random.randint(5, size =(5,4))
print(a)

[[4 0 1 2]
 [3 3 2 0]
 [3 2 3 0]
 [4 0 1 4]
 [1 3 0 3]]


In [ ]:
# task10:
import numpy as np

n_samples = 5
n_features = 4
x = np.random.rand(n_samples, n_features)
y = np.random.randint(0, 2, n_samples)

print('x = \n', x)
print('y = \n', y)

x = 
 [[0.36405202 0.97982793 0.89686115 0.54614527]
 [0.51262776 0.09332935 0.89823006 0.31719235]
 [0.30753466 0.8450031  0.85432057 0.84477217]
 [0.24464267 0.67318171 0.19378767 0.06929828]
 [0.37761659 0.82937141 0.63376006 0.17413488]]
y = 
 [0 1 1 1 0]


In [ ]:
# task11:
def extract_subset(x, y, y0):
    return x[y==y0, :]


n_patterns = 5
n_features = 4
x = np.random.rand(n_patterns, n_features)
y = np.random.randint(0, 2, n_patterns)

y0 = 0
x0 = extract_subset(x, y, y0)

print('x: \n', x)
print('y: \n', y)
print(y0, ':\n', x0)


x: 
 [[0.1077762  0.05893042 0.06587168 0.71725671]
 [0.75411481 0.46159838 0.31065949 0.77786317]
 [0.86888083 0.57871265 0.54664066 0.44720425]
 [0.78988755 0.60324721 0.08104275 0.28811157]
 [0.42587608 0.85700439 0.37430267 0.21627543]]
y: 
 [0 1 0 0 1]
0 :
 [[0.1077762  0.05893042 0.06587168 0.71725671]
 [0.86888083 0.57871265 0.54664066 0.44720425]
 [0.78988755 0.60324721 0.08104275 0.28811157]]


In [ ]:
# task12:
import pandas as pd
data = pd.read_csv('/content/iris.csv')

In [ ]:
data.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [ ]:
data["sepal_length"].mean()

5.843333333333334

In [ ]:
data["sepal_length"].median()

5.8

In [ ]:
data["sepal_length"].std()

0.828066127977863